// <auto-generated />
using HeartsTracker.Dal.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HeartsTracker.Dal.Migrations
{
    [DbContext(typeof(HeartsTrackerContext))]
    [Migration("20180315071204_AddedGameAndScoreEntities")]
    partial class AddedGameAndScoreEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeartsTracker.Dal.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDateTime");

                    b.Property<DateTime>("StartDateTime");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("HeartsTracker.Dal.Entities.GamePlayer", b =>
                {
                    b.Property<int>("GameId");

                    b.Property<int>("PlayerId");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GamePlayer");
                });

            modelBuilder.Entity("HeartsTracker.Dal.Entities.GameRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDateTime");

                    b.Property<int>("GameId");

                    b.Property<DateTime>("StartDateTime");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameRound");
                });

            modelBuilder.Entity("HeartsTracker.Dal.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Colour");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName");

                    b.Property<string>("PlayerName");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("HeartsTracker.Dal.Entities.PlayerScore", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<int>("RoundId");

                    b.Property<int?>("GameRoundId");

                    b.Property<int>("Score");

                    b.HasKey("PlayerId", "RoundId");

                    b.HasIndex("GameRoundId");

                    b.ToTable("PlayerScore");
                });

            modelBuilder.Entity("HeartsTracker.Dal.Entities.GamePlayer", b =>
                {
                    b.HasOne("HeartsTracker.Dal.Entities.Game", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HeartsTracker.Dal.Entities.Player", "Player")
                        .WithMany("GamePlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HeartsTracker.Dal.Entities.GameRound", b =>
                {
                    b.HasOne("HeartsTracker.Dal.Entities.Game", "Game")
                        .WithMany("GameRounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HeartsTracker.Dal.Entities.PlayerScore", b =>
                {
                    b.HasOne("HeartsTracker.Dal.Entities.GameRound", "GameRound")
                        .WithMany("Scores")
                        .HasForeignKey("GameRoundId");

                    b.HasOne("HeartsTracker.Dal.Entities.Player", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
